parameters:
#    blogger_upload.example.class: Blogger\UploadBundle\Example

services:
#    blogger_upload.example:
#        class: %blogger_upload.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
