# src/Blogger/BlogBundle/Resources/config/routing.yml
BloggerBlogBundle_homepage:
    pattern:  /
    defaults: { _controller: BloggerBlogBundle:Page:index }
    requirements:
        _method:  GET
        
BloggerBlogBundle_about:
    pattern:  /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
    requirements:
        _method:  GET        

BloggerBlogBundle_contact:
    pattern:  /contact
    defaults: { _controller: BloggerBlogBundle:Page:contact }
    requirements:
        _method: GET|POST
        
BloggerBlogBundle_admin:
    pattern:  /admin
    defaults: { _controller: BloggerBlogBundle:Admin:index }
    requirements:
        _method: GET
       
BloggerBlogBundle_comment_create:
    pattern:  /comment/{blog_id}
    defaults: { _controller: BloggerBlogBundle:Comment:create }
    requirements:
        _method:  POST
        blog_id:  \d+
        
BloggerBlogBundle_comment_remove:
    pattern:  /admin/comment/remove/{id}
    defaults: { _controller: BloggerBlogBundle:Comment:remove }
    requirements:
        _method:  GET
        id:  \d+
        
BloggerBlogBundle_blog_show:
    pattern:  /{id}
    defaults: { _controller: BloggerBlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+
        
BloggerBlogBundle_blog_update:
    pattern:  /admin/update/{id}
    defaults: { _controller: BloggerBlogBundle:Blog:update }
    requirements:
        _method:  GET|POST
        id: \d+
        
BloggerBlogBundle_blog_add:
    pattern:  /admin/add/
    defaults: { _controller: BloggerBlogBundle:Blog:add }
    requirements:
        _method:  GET|POST