parameters:
#    blogger_security.example.class: Blogger\SecurityBundle\Example

services:
#    blogger_security.example:
#        class: %blogger_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
